source_list:
  - SB
  - OL
  - CP
  - ADDR

target_list:
  - REGIS_DIM
  - CHILD_DIM
  - RTL_TXN_FACT

SB:
  mysql_conf:
    dbtable: testdb.TRANSACTIONSYNC
    partition_column: App_Transaction_Id

OL:
  sftp_conf:
    filetype: csv
    delimiter: |
    directory: /home/ubuntu/data
  filename: receipts_delta_GBR_14_10_2017.csv

CP:
  s3_conf:
    s3_bucket: kishor.cstech1
  filename: KC_Extract_1_20171009.csv

ADDR:
  mongodb_config:
    database: customer
    collection: address

REGIS_DIM:
    tableName: DATAMART.REGIS_DIM
    sourceData:
      - CP
      - ADDR
    loadingQuery: >
        SELECT
            FN_UUID() as REGIS_KEY, REGIS_CNSM_ID AS CNSM_ID, REGIS_CTY_CODE AS CTY_CODE,
            REGIS_ID, REGIS_DATE, REGIS_LTY_ID AS LTY_ID, REGIS_CHANNEL, REGIS_GENDER, REGIS_CITY, INS_DT
        FROM
            (SELECT
                DISTINCT a.REGIS_CNSM_ID, CAST(a.REGIS_CTY_CODE AS SMALLINT), CAST(a.REGIS_ID AS INTEGER),
                a.REGIS_LTY_ID, a.REGIS_DATE, a.REGIS_CHANNEL, a.REGIS_GENDER, a.REGIS_CITY,
                b.state, b.city, b.street, a.ins_dt
            FROM
                CP a join ADDR b
                    on a.REGIS_CNSM_ID=b.consumer_id
            WHERE
                a.ins_dt = '2020-11-02'
            ) cp

CHILD_DIM:
  tableName: DATAMART.CHILD_DIM
  sourceData:
    - CP
  loadingQuery: >
      SELECT
          FN_UUID() CHILD_KEY, REGIS_CNSM_ID, REGIS_CTY_CODE, CHILD_ID, CHILD_NB, CHILD_GENDER, ins_dt
       FROM
           (SELECT DISTINCT REGIS_CNSM_ID, REGIS_CTY_CODE, CHILD_ID, CHILD_NB, CHILD_GENDER, ins_dt
       FROM
          CP
       WHERE
          CAST(ins_dt AS DATE) = '2020-11-02'
          AND CHILD_ID IS NOT NULL
      ) CP

RTL_TXN_FACT:
  sourceData:
    - SB
    - OL
  sourceTable:
    - DATAMART.REGIS_DIM

  tableName: DATAMART.RTL_TXN_FCT
  loadingQuery: >
      SELECT
          FN_UUID() AS RTL_TXN_KEY, CAST(TXN.APP_TRANSACTION_ID AS STRING)AS TXN_ID, SIZE(split(REC.PRODUCTS, ',')) AS TXN_ITEM_QTY,
          TRANSACTION_POINT_VALUE AS TXN_LOY_VAL_STD_CCY, 0 AS TXN_GROSS_MNY_STD_CCY, TRANSACTION_RETAIL_VALUE AS TXN_GROSS_MNY_LCL_CCY,
          -1 AS MNY_LCL_CCY_TYPE_KEY, TRANSACTION_EXTERNAL_REFERENCE AS RTL_TXN_TYPE_KEY, ACTIVITY_TIMESTAMP AS TXN_TS,
          CAST(ACTIVITY_TIMESTAMP AS DATE) AS TXN_DT_KEY, HOUR(ACTIVITY_TIMESTAMP) AS TXN_TM_HOUR, MINUTE(ACTIVITY_TIMESTAMP) AS TXN_TM_MINUTE,
          SECOND(ACTIVITY_TIMESTAMP) AS TXN_TM_SECOND, '-1' AS CHNL_KEY, REG.CNSM_ID AS CNSM_ID,
          "@NULL@" AS RTL_TXN_EXT_DEC_1, "@NULL@" AS RTL_TXN_EXT_DEC_2, REC.BASE_POINT_VALUE AS
          RTL_TXN_EXT_DEC_3, MOBILE_UID AS RTL_TXN_EXT_CHAR_1, MOBILE_OS AS RTL_TXN_EXT_CHAR_2, PRODUCTS AS RTL_TXN_EXT_CHAR_3,
          RECEIPT_STATUS AS RTL_TXN_EXT_CHAR_4, CAST(MSG_CODE AS BIGINT) AS RTL_TXN_EXT_CHAR_5, TXN.ins_dt AS INS_TS
      FROM
          SB TXN LEFT OUTER JOIN OL REC
          ON (TXN.APP_TRANSACTION_ID = REC.SBLP_TRANSACTION_ID)
          LEFT OUTER JOIN REGIS_DIM REG
          ON REC.LOYALTY_ID = REG.CNSM_ID
      WHERE
           TXN.INS_DT = '2020-11-02'
                  AND (REC.ins_dt = '2020-11-02' OR REC.ins_dt is NULL )
s3_conf:
  s3_bucket: vnagthane
  staging_dir: pg_staging

redshift_conf:
  filetype: csv
  delimiter: |
  dbtable: DATAMART.REGIS_DIM


